### ISSUE TITLE
Rendered images not showing in Chrome

### ISSUE THREAD

**Issue by jfinstrom** [chjj/ttystudio#11]
This technically isn't a you problem per se. 

With your fixes to the other issues in the last few days (thanks you rock) I have finally been able to render  a gif. When I open it in chrome the first frame shows then it goes away.  If I upload that gif to imgur whatever they do to re-encode it seems to correct the issue. 

The rendered gif https://www.dropbox.com/s/la4mfkzpj383o46/fwconsole.gif?dl=0
The imgur gif https://www.dropbox.com/s/ivg0z0f2cogebwr/OrqQBbK.gif?dl=0

I don't know what the difference is or if maybe it is as simple as passing a flag of some sort

**Comment by jfinstrom** [comment]
Note the rendered file seems to work fine in "Not Chrome" so it is something specific to their handling of things

**Comment by chjj** [comment]
You're right. Works fine in firefox, stops in chrome. The imgur version works in both. Could you provide me with a gist of your `fwconsole.frames.json`?

**Comment by chjj** [comment]
Just a quick diff of the two gifs, I think I noticed what's wrong. There's a problem with the LZWEncoder I borrowed. Will fix tonight. Thanks for bringing this up. This is a serious issue.

**Comment by chjj** [comment]
@jfinstrom,

This should be fixed. It was a typo passing in args to the LZWEncoder, so smaller frames thought they had larger dimensions. Firefox gracefully handles this apparently. Chromium does not. As an extra benefit: this optimizes gif size **a lot** more (a 554kb gif becomes 353kb). Thanks for bringing this up.

**Comment by jfinstrom** [comment]
Confirmed fixed. Thanks
