### ISSUE TITLE
Install Fails on Debian 8 Jessie

### ISSUE THREAD

**Issue by iku000888** [chjj/ttystudio#12]
**_Nube Alert**_

Its my first ever time dealing with node and npm so there is probably a lot that I am missing.

I did the following:
1. apt-get install node
2. apt-get install npm
3. npm install ttystudio

and I get the following output:

root@debian:/home/ikuru# npm install ttystudio
/

> pty.js@0.2.8 install /home/ikuru/node_modules/ttystudio/node_modules/pty.js
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-686-pae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ikuru/node_modules/ttystudio/node_modules/pty.js
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.8 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "ttystudio"
npm ERR! cwd /home/ikuru
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ikuru/npm-debug.log
npm ERR! not ok code 0
root@debian:/home/ikuru# npm install -g ttystudio
/

> pty.js@0.2.8 install /usr/local/lib/node_modules/ttystudio/node_modules/pty.js
> node-gyp rebuild

gyp: Call to 'node -e "require('nan')"' returned exit status 1. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:344:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:809:12)
gyp ERR! System Linux 3.16.0-4-686-pae
gyp ERR! command "nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/ttystudio/node_modules/pty.js
gyp ERR! node -v v0.10.29
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! pty.js@0.2.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pty.js@0.2.8 install script.
npm ERR! This is most likely a problem with the pty.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pty.js
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "ttystudio"
npm ERR! cwd /home/ikuru
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ikuru/npm-debug.log
npm ERR! not ok code 0

Sorry again for the nube-ish issue & thanks in advance!

**Comment by chjj** [comment]
Either the `nan` module isn't installed (unlikely), or `node` isn't in your `$PATH`. Some distros renamed the `node` binary to `nodejs` so that might be the problem. A hacky solution would be to `$ sudo ln -s /usr/bin/nodejs /usr/bin/node`. Check to see if node is there first with a `$ type node` or `$ which node`.

**Comment by iku000888** [comment]
ikuru@debian:~$ which nodejs
/usr/bin/nodejs

Seems like it is the later case.

**Comment by iku000888** [comment]
Seems like it worked!
Thank you very much!

```
root@debian:/home/ikuru# npm install ttystudio
|  
> pty.js@0.2.8 install /home/ikuru/node_modules/ttystudio/node_modules/pty.js
> node-gyp rebuild

make: Entering directory '/home/ikuru/node_modules/ttystudio/node_modules/pty.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/obj.target/pty.node
  SOLINK_MODULE(target) Release/obj.target/pty.node: Finished
  COPY Release/pty.node
make: Leaving directory '/home/ikuru/node_modules/ttystudio/node_modules/pty.js/build'
ttystudio@0.0.10-1 node_modules/ttystudio
├── term.js@0.0.5
├── blessed@0.1.7
└── pty.js@0.2.8 (extend@1.2.1, nan@1.8.4)
```
