### ISSUE TITLE
ttystudio ignores `^C` signal

### ISSUE THREAD

**Issue by joshblum** [chjj/ttystudio#8]
If you want to cancel the writing of a gif you have to manually find the process number and kill it. It would be much easier if standard `^C` worked.

**Comment by austinpray** [comment]
Yep. Once you start it you can't stop it. 

+1

**Comment by chjj** [comment]
This is likely due to blessed setting raw mode. I added a line to set the terminal input back to cooked, but I'm not sure it works.

Doing:

``` bash
$ ttystudio frames.json
$ ttystudio frames.json output.gif
```

Should let you ^C it, since blessed is never instantiated.
